// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordShop.Api.Data;

#nullable disable

namespace RecordShop.Api.Migrations
{
    [DbContext(typeof(RecordShopContext))]
    [Migration("20260507102018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecordShop.Api.Models.DataModels.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Michael Jackson",
                            Price = 10.99m,
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "AC/DC",
                            Price = 9.49m,
                            Title = "Back In Black"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Pink Floyd",
                            Price = 15.00m,
                            Title = "The Dark Side of the Moon"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Nirvana",
                            Price = 5.99m,
                            Title = "Nevermind"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Fleetwood Mac",
                            Price = 12.50m,
                            Title = "Rumours"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "The Beatles",
                            Price = 14.99m,
                            Title = "Abbey Road"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
